Dangerfile
**What's in this PR?**
* Adds a check for `// TODO` comments left in modified and added files to the shared `Dangerfile`
=> Check PR's for todo comments left in modified files

Dangerfile
* If a user modifies a file with outdated copyright header there shouldn't be a warning.
=> Do not warn about outdated copyright headers in modified files

Dangerfile
* Remove the colon to match `[WIP]` as well.
=> Match [WIP] in PR title

Dangerfile, Gemfile, Gemfile.lock, build.sh
We were not running analyzer on CI which can potentially uncover some bugs.
* Updated build scripts to always do `analyze` step 
* Posting results of the build command to Danger summary
Unfortunately analyzing the project doesn't come for free and increases compile time quite a bit (up to 100%). However in most cases it is not a problem as most of the time is spent on running tests anyway.
=> Running analyzer and posting results in PR comments

Dangerfile
* Removed joke about copyright year that is not very funny anymore
=> Changed wording of copyright year warning

build.sh, post_test.sh, test.sh
At the moment we don't track code coverage on UI project but it might be useful to actually start doing it.
=> Enabled code coverage tracking on UI project

Fastlane/Frameworks, Fastlane/MergePR, Jenkins/MergePR
This is used when release is triggered from comment
=> Added config for merging PRs on GitHub

Jenkins/UI/AVS.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy
Added Jenkins pipelines for Internal and AVS builds that were previously configured as regular Jenkins jobs.
=> Added AVS and Internal builds

Jenkins/UI/Build.groovy
Increase timeout since the checkout times out when starting from a fresh workspace
=> Increase timeout

Azure/build-and-test/build-and-test.yml, Azure/framework-pipelines.yml, Azure/release-framework/release-framework.yml
=> update for Xcode 10.2

Jenkins/UI/Build.groovy
replace hockey app with app center
=> feature: app center support

Jenkins/UI/Build.groovy, Jenkins/UI/BuildAppStore.groovy
- remove the retired hockey stage for general building lane
- replace hockey with app centre in App Store build lane
=> remove hockey app stage  and replaced with app center stage

Azure/build-and-test/Fastfile, Azure/build-and-test/build-and-test.yml, Azure/framework-pipelines.yml, Azure/release-framework/release-framework.yml, Jenkins/UI/Build.groovy, Jenkins/UI/Playground.groovy
Update the azure scripts for Xcode 11.3
=> [Chore] Migrate to Xcode 11.3

Jenkins/UI/AppStore.groovy
Copy the GitHub token access lines form `build.groovy`
=> add missing GitHub token for App Store pipeline

Jenkins/UI/AVS.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy, Jenkins/UI/Playground.groovy
Copy the Xcode version parameter from Playground to other pipelines
=> support XCode version as parameter

Jenkins/UI/AVS.groovy, Jenkins/UI/AppStore.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy
Change pipeline default Xcode version to 12.4
=> change default Xcode version to 12.4

Azure/build-and-test/build-and-test.yml, Azure/framework-pipelines.yml
ref:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
=> bump to macOS 11 and Xcode 13.1

Jenkins/UI/AVS.groovy, Jenkins/UI/AppStore.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy, Jenkins/UI/Playground.groovy
Change  default Xcode version to Xcode 13.1
=> feature: change default xcode version to 13.1

.github/workflows/mergePR.yml
create a shared workflow
----
----
_Attachments …
=> feat: Create shared mergePR.yml

.github/workflows/mergePR.yml
=> feat: add comment for merge failure

.github/workflows/mergePR.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-774" title="SQPIT-774" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-774</a>  Move GitHub workflows to https://github.com/wireapp/.github
</td></table>
<br />
----
----
_If there are some other pull requests related …
=> fix: Update mergePR.yml SQPIT-774

.github/workflows/mergePR.yml
=> fix: do not exit

.github/workflows/mergePR.yml
=> fix: equal space

.github/workflows/mergePR.yml
=> fix: capture output of gh pr merge

.github/workflows/mergePR.yml
=> fix: Update mergePR.yml

.github/workflows/mergePR.yml
=> fix: check before tag_version

Jenkins/UI/Build.groovy
=> fix: set dev path for xcode 12.4

Jenkins/UI/Build.groovy
=> fix: if syntax in script

Jenkins/UI/Build.groovy
=> fix: clean up and print Xcode ver input

Jenkins/UI/AppStore.groovy
=> fix: build app store build with 12.4 by default

.github/workflows/mergePR.yml
=> fix: combine comment

.github/workflows/mergePR.yml
=> fix: replace next version action

.github/workflows/mergePR.yml
=> fix: quote

.github/workflows/createBumpPR.yml
=> feat: bump PR

.github/workflows/createBumpPR.yml
change secret  to IOS_RELEASE_DISPATCH_SECRET
=> fix: Update createBumpPR.yml

.github/workflows/createBumpPR.yml
=> fix: get PAT from input

.github/workflows/createBumpPR.yml
=> feat: check cart file size

.github/workflows/mergePR.yml
to trigger checks, default token would not work
ref: https://stackoverflow.com/a/69169858/353911
----
----
_Specify here …
=> fix: use PAT instead of default GitHub token

.github/workflows/mergePR.yml
=> fix: missing user email and name

.github/workflows/createBumpPR.yml
to fix check not triggered by this workflow issue
----
----
_Specify here any other facts that you think are important for …
=> fix: change default token to user's token

.github/workflows/createBumpPR.yml
=> fix: gh auth before create PR

.github/workflows/createBumpPR.yml
=> fix: gh auth before checkout to fix API limit error

.github/workflows/createBumpPR.yml
=> chore: split into steps

.github/workflows/createBumpPR.yml
fix local $branch not passed to later step
=> fix: create branch failed

Jenkins/UI/BuildAppStore.groovy
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-785" title="SQPIT-785" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-785</a>  fix: fastlane needs 2FA code after the session is expired
</td></table>
<br />
----
----
Use api key to auth .ipa upload instead of user and password
The secret json file is added to [jenkins]/credentials/store/system/domain/_/credential/app_store_connect_api_key/
ref: https://docs.fastlane.tools/app-store-connect-api/
=> feat: replace user and passwd with app key file SQPIT-785

Jenkins/UI/Build.groovy
=> fix: disableConcurrentBuilds syntax

Jenkins/UI/Build.groovy
=> fix: undo deprecated option

Azure/build-and-test/Fastfile
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-799" title="SQPIT-799" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-799</a>  fix: flaky test on wire-ios
</td></table>
<br />
Reverts wireapp/wire-ios-shared-resources#91
=> revert: fix: undo retry failed tests SQPIT-799

Azure/build-and-test/build-and-test.yml, Azure/framework-pipelines.yml
Add parameters to allow selection Xcode 12 or 13 when build and test a framework.
=> feat: support Xcode app name parameter in framework pipeline

Jenkins/UI/BuildAppStore.groovy
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-785" title="SQPIT-785" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQPIT-785</a>  fix: fastlane needs 2FA code after the session is expired
</td></table>
<br />
Reverts wireapp/wire-ios-shared-resources#86
=> revert: feat: replace user and passwd with app key file SQPIT-785

Azure/build-and-test/build-and-test.yml
----
----
disable failing steps about artifacts upload
----
----
----
=> chore: disable artifacts upload

.github/workflows/mergePR.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-36" title="IC-36" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-36</a>  Update list of admins for MergePR action
</td></table>
<br />
----
----
Remove old users from the admin list.
----
----
----
=> chore: update list of admins IC-36

Jenkins/UI/AppStore.groovy
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-42" title="IC-42" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-42</a>  Build App Store build with Xcode 13
</td></table>
<br />
----
----
Build App Store build with Xcode 13 by default since from April 25 we need to submit builds using Xcode 13. Eventually we can remove the option to build with Xcode 12 altogether.
----
----
----
=> chore: build App Store build with Xcode 13 by default IC-42

Jenkins/UI/AVS.groovy, Jenkins/UI/AppStore.groovy, Jenkins/UI/Build.groovy, Jenkins/UI/BuildAppStore.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy, Jenkins/UI/Playground.groovy
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-47" title="IC-47" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-47</a>  Migrate to Xcode 13.3
</td></table>
<br />
----
----
Update groovy scripts to have updated Xcode version 13.2.1
Update scripts according to required Xcode versions
----
----
=> chore: update Jenkins groovy scripts for Xcode 13.2.1 IC-47

Jenkins/UI/AVS.groovy, Jenkins/UI/AppStore.groovy, Jenkins/UI/BuildAppStore.groovy, Jenkins/UI/Develop.groovy, Jenkins/UI/Internal.groovy, Jenkins/UI/Playground.groovy
----
----
Set the default Xcode version to 13.2.1. The current default is 13.1.
----
----
----
=> chore: set default xcode version to 13.2.1

.github/workflows/mergePR.yml
----
----
The list of admins contains a syntax error, there shouldn't be any commas.
----
----
----
=> fix: syntax error in list of admins

Fastlane/Pluginfile, Gemfile.lock, Jenkins/UI/Build.groovy
----
----
Add new step to include datadog dsyms for builds 
----
----
----
=> feat: add step for datadog dsyms

Jenkins/UI/Build.groovy
----
----
There was a syntax error in the build script using nodejs for Datadog upload.
Here's the build working https://10.10.124.23/job/client-ios-build-pipeline/5622/
----
----
=> fix: script using nodejs

Jenkins/UI/Beta.groovy, Jenkins/UI/BuildAppStore.groovy, Jenkins/UI/BuildAppStoreMono.groovy, Jenkins/UI/BuildMono.groovy, Jenkins/UI/UpdateProvisioningProfiles.groovy
----
----
An error on fastlane locked out the account, so it is not possible to upload versions to AppStore
https://github.com/fastlane/fastlane/issues/20530
Use AppStore connect authentication key to upload ipa and interact with appStore connect instead of username and password.
_Attachments like images, videos, etc. (drag and drop in the text box)_
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
=> feat: use AppStore connect api auth key

Jenkins/Release.groovy, Jenkins/UI/Beta.groovy, Jenkins/UI/Build.groovy, Jenkins/UI/BuildAppStoreMono.groovy, Jenkins/UI/BuildMono.groovy, Jenkins/UI/TestPlan.groovy
----
----
Fix of setting GITHUB_AVS_ACCESS_TOKEN env for avs download version
----
----
----
=> fix: add github token for avs

Jenkins/UI/AppStoreMono.groovy, Jenkins/UI/BuildAppStoreMono.groovy, Jenkins/UI/BuildMono.groovy, Jenkins/UI/DevelopMono.groovy, Jenkins/UI/InternalMono.groovy, Jenkins/UI/PlaygroundMono.groovy
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-133" title="IC-133" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />IC-133</a>  Update jenkins pipeline scripts
</td></table>
<br />
----
----
upgrade Xcode version to 14.2 on jenkins groovy scripts
Added an option Xcode 14.2 to the script , so that it can be selected as one of the choice in jenkins job
----
----
----
=> chore: upgrade xcode version to 14.3 on jenkins pipelines IC-133

Jenkins/UI/AppStoreMono.groovy, Jenkins/UI/Beta.groovy, Jenkins/UI/BuildAppStore.groovy, Jenkins/UI/BuildMono.groovy, Jenkins/UI/DevelopMono.groovy, Jenkins/UI/InternalMono.groovy, Jenkins/UI/PlaygroundMono.groovy
----
----
Add support for Xcode 14.2
----
----
----
=> chore: add Xcode version 14.2

Gemfile, Gemfile.lock
----
----
Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile
----
----
----
=> fix: error on trainer fastlane plugin
