Dangerfile

The previous search for TODO comments was also warning if the string "todo" appeared anywhere in a method name. I also added the line number for faster look-up.

Update todo regex and add line number for warning

---

Dangerfile

**What's in this PR?**
* The `content` variable was not in the scope of the missing copyright header warning anymore.

Add minified content variable back

---

Dangerfile

**What's in this PR?**
Warn if an entry in the Cartfile.resolved is still pinned to a commit instead of a tag

Warn if an entry in the Cartfile.resolved is still pinned to a commit

---

Dangerfile

* The new Danger 3.2.0 supports adding GitHub inline comments, which means we can add line comments if there are any TODOs etc. left. (see https://github.com/danger/danger/blob/master/CHANGELOG.md#320)

Use new Danger 3.2.0 features

---

Dangerfile

If we have a pull request that is often updated (e.g. an integration PR) then Danger comments are not very useful.

Skipping Danger for WIP pull requests

---

Dangerfile
Fastlane/Frameworks
Jenkinsfile

The plan is to unify the build scripts and use same steps for testing PRs and making a release.
The last bit missing was to upload code coverage information and run Danger after tests. There are some variables automatically set when running on CircleCI (which repository it is, branch name and commit SHA) that we need to supply manually on Jenkins.
Storing Codecov.io token in Jenkins credentials and also overriding PATH so that it would be the same on all nodes.

Uploading code coverage and running Danger

---

Fastlane/MergePR

Small improvement to the "magic phrase" merge script - the PR branch will be deleted after merging the changes.

Deleting PR branch after merging

---

Dangerfile
Fastlane/Frameworks

Danger now prints out test coverage percentages for files that have `calling` in their name/path. This shows an approximate state of calling code testing.

Added test coverage tracking for all classes related to calling

---

Azure/build-and-test/Fastfile
Azure/framework-pipelines.yml

Sometimes when testing PRs the testsuite fails because we have unreliable/flaky tests. We should of course fix them in the long run, but most of the time we just retry the job. This however takes a lot of time because we rebuild the project and run the full test suite.
This PR adds another step when testing:
1. Run full test suite, but do not fail build if any tests fail
1. Parse the test results from `test/report.junit`.
2. Look for test classes that have failing tests.
3. Rerun only those tests.
4. Fail if they do not pass successfully.
The `junit` file is a simple XML that is generated by Fastlane. It has quite simple and regular structure so it should be fine to use regexps for parsing lines that we are interested in.
Fixes https://github.com/wireapp/ios-architecture/issues/61

Retry failed tests

---

Jenkins/UI/AppStore.groovy
Jenkins/UI/Build.groovy
Jenkins/UI/BuildAppStore.groovy

* Added pipeline that builds only AppStore binary and uploads to AppStoreConnect. It does not run tests.
* Added pipeline that listens to changes in `release/*` branches and triggers RC and AppStore build.
Another build pipeline for AppStore build was needed because it is very different from other kinds of builds i.e. it does not upload a build to Hockey, no need to run tests again etc.

AppStore builds

---

Jenkins/UI/Build.groovy

`QA: build for simulator` stage actually is a zipping task and do not affect to `Test` stage.
This PR put these steps in parallel. (`Test` step is about 3 min and `QA: build for simulator` is about 40 sec. After this improvement, both of them can be done in about 3 min and save the time for `QA: build for simulator`)

Preformance improvement - Test & QA: build for simulator in parallel

---

Jenkins/UI/BuildAppStore.groovy

Due to the missing symbol in framework issue, the build for release step in App Store build pipeline may fail. This PR added try catch in the stage. When error is catch, build again without symbols.

feature: try catch release build and rebuild without symbol

---

Azure/build-and-test/build-and-test.yml
Azure/release-framework/Fastfile

Create framework release in `XCFramework` format instead of universal bundle.
This PR should not be merged before fully tested on `billypchan` fork, and got approval from the iOS team.

Feature: create release in XCFramework format

---

Azure/build-and-test/Fastfile

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-799" title="SQPIT-799" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-799</a>  fix: flaky test on wire-ios
</td></table>
<br />
----
----
When tests crashed or failed, the test suit result still mark as passed.
We added a retry test logic:
https://github.com/wireapp/wire-ios-shared-resources/pull/28
But this logic can not capture when some test crashed or failed in some cases, e.g. 
https://github.com/wireapp/wire-ios-sync-engine/pull/1614
Undo the retry test logic, if we find any flaky test, use XCT expected fail or XCT skip for expect condition.
set `number_of_retries` to 1 to retry …

fix: undo retry failed tests SQPIT-799

---

Azure/framework-pipelines.yml
Azure/release-framework/release-framework.yml

follow up of https://github.com/wireapp/wire-ios-shared-resources/pull/70. Add parameters to allow selection Xcode 12 or 13 when release a framework.

fix: set release framework xcode app

---

Azure/build-and-test/build-and-test.yml

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/IC-31" title="IC-31" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />IC-31</a>  Re-enable test artefacts uploading to Azure
</td></table>
<br />
This reverts commit 914c33aea92f63537bc3aaa30f78a9cf0b910b7c.
----
----
This PR re-enables the steps to upload the test results to azure. They were disabled previously because they were failing for an unknown reason, but it appears that this is no longer the case.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in …

chore: enable test artifact upload IC-31

---

Jenkins/UI/BuildAppStore.groovy

----
----
Running the `client-ios-build-appstore-pipeline` via the Jenkins web interface fails
The `xcode_version` parameter is missing 
Add a choice parameter for the `xcode_version` to the pipeline
----
----

fix: client-ios-build-appstore-pipeline parameters

---

.github/workflows/mergePR.yml

----
----
Some devs can't release frameworks.
They're not on the admin list.
Add them.
----
----
----

chore: add more people to merge pr command

---

Jenkins/UI/AppStoreMono.groovy

----
----
When merging into `release/frida` branch the public release is triggered and mix the Public RC builds and Frida RC builds on AppStore connect.
This skips the trigger for this branch.
----
----
----

chore: skip build RC public to testflight when merge on frida branch

---

Jenkins/UI/AppStoreMono.groovy

----
----
AppStore release job is still triggering by `release/frida`.
The build [#5543] was indeed skipped thanks to this change
----
----
----

fix: wrong branch environment variable
